version: '3.7'

services:
  # =migrations
  migrations:
    image: "sindriainc/migrations:latest"
    container_name: "${APP_NAME}-migrations"
    volumes:
      - "${MIGRATIONS_CODE_PATH}:${APP_CODE_PATH}/database"
      - "./migrations.env:${APP_CODE_PATH}/.env"
    hostname: "${APP_NAME}-migrations.local"
    networks:
      vpc:
        ipv4_address: "${SINDRIADOCK_MIGRATIONS_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}-migrations.local"

# =networks
networks:
  vpc:
    name: "vpc_${APP_NAME}"
    driver: bridge
    ipam:
      config:
        - subnet: ${SINDRIADOCK_NETWORK_SUBNET}
